### ISSUE TITLE
Use raster interrupts for C64

### ISSUE THREAD

**Issue by matozoid** [Fabrizio-Caruso/CROSS-CHASE#3] opened 2017-10-07 12:05 UTC
Saw this video: https://www.youtube.com/watch?v=VVXqgPCUQCM
and thought refreshing the screen somewhere outside the displayable area would stop the flickering.

Thanks for making new 8-bit stuff :-)

**Comment by Fabrizio-Caruso** [comment] 2017-10-09 14:50
Hi! Thanks for following my project!
I do not understand the issue. What is flickering for you that should not be flickering?
The green slowdown power-up is supposed to flicker.
The enemies are redefined characters and move in a grid. 
Their jerky movement is the expected behavior (in the current implementation at least for the moment).

**Comment by Fabrizio-Caruso** [comment] 2017-10-09 16:48
If I try to do something like
	while(VIC.rasterline>40){}
	cputc(image->_imageData); 

i.e., wait for a low value of the rasterline before writing onto video memory, I do not see any improvement and the game is significantly slowed-down.

**Comment by matozoid** [comment] 2017-10-09 20:56
Okay, with flickering I mean that every time a monster moves it disappears for a splits second. So instead of moving from a to b, it seems to disappear from a and reappear on b.

With a raster interrupt I mean putting your code in an interrupt handler that fires on a specific rasterline. It's what most games do to hide screen updates.

If this can't be done from C then this issue can be closed, I guess :-)

**Comment by Fabrizio-Caruso** [comment] 2017-10-09 21:24
This cannot be done reasonably in C because it would require handling interrupts in C, which is (close to) impossible.
Some cross-compilers provide some tools but discourage to use them (e.g., CC65) to do anything time-critical. 
I am not writing a C64 version of the game. If you look at the code, you'll see that all versions share the same code except very few bits about input, sound and graphics (and even this is shared among many targets).

My project is about a universal 8 bit game (i.e., it has to be coded in a way that a single Makefile can generate binaries for nearly all 8 bit computers from the same code). The game should be fun and very playable. Eye-candy is not the highest priority but I DO plan to improve it. In the future I may use sprites instead of simple characters (I have already implemented a prototype).

**Comment by Fabrizio-Caruso** [comment] 2017-10-09 21:33
So, what you ask is not impossible but extremely hard in C. It would require lots of Assembly and therefore it would not be in the scope of a universal project. (I have used small fragments of Z80 Assembly for sound in Amstrad CPC and graphics in VG-5000 because I had not much choice).
I will close the issue BUT I will try to do my best to improve graphics because that is where my little game is a bit weak. (I am actually doing it right now).
Thanks a lot for following my project!

**Closed** 2017-10-09 21:54 UTC

**Comment by matozoid** [comment] 2017-10-09 22:05
And thank you for considering this :-)
